version: 0.2

env:
  parameter-store:
    SES_IDENTITY: "/ai-job-agent/prod/ses-identity"
    ARTIFACT_BUCKET: "/ai-job-agent/prod/artifact-bucket"
    FRONTEND_BUCKET_NAME: "/ai-job-agent/prod/frontend-bucket-name" # Nueva variable

phases:
  install:
    # ... (sin cambios) ...

  build:
    # ... (sin cambios) ...

  post_build:
    commands:
      - echo "Iniciando la fase de Post-Build..."
      # 1. Empaquetar el backend (Lambdas)
      - sam package --output-template-file packaged.yaml --s3-bucket ${ARTIFACT_BUCKET}
      # 2. Desplegar los archivos del frontend al bucket de S3
      - echo "Desplegando archivos del frontend a S3..."
      - aws s3 sync frontend/ s3://${FRONTEND_BUCKET_NAME}/ --delete

artifacts:
  files:
    - packaged.yaml


