AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ai-job-agent
  Complete infrastructure for the AI Job Search Agent, including Cognito authentication.

Globals:
  Function:
    Timeout: 60
    Runtime: python3.9
    MemorySize: 256
    # ... (rest of Globals section)

Resources:
  # --- Authentication ---
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AI-Job-Agent-Users
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      AutoVerifiedAttributes: [email]
      
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: AI-Job-Agent-Web-Client
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
        - Google
        - Azure # Represents Microsoft
      CallbackURLs:
        - http://localhost:8080/dashboard.html # For local testing
        - https://YOUR_PRODUCTION_URL/dashboard.html # IMPORTANT: Add your production URL here
      LogoutURLs:
        - http://localhost:8080/auth.html
        - https://YOUR_PRODUCTION_URL/auth.html
  
  # --- S3 Buckets, DynamoDB Tables, and Lambda Functions from previous version ---
  # ... (All your other resources like S3, DynamoDB, and Lambdas go here without changes)

Outputs:
  Region:
    Description: "AWS Region"
    Value: !Ref AWS::Region
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref CognitoUserPoolClient

