AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ai-job-agent
  Infraestructura completa con frontend en S3 y despliegue automatizado.

Parameters:
  SESVerifiedIdentity:
    Type: String
    Description: El correo o dominio verificado en SES para enviar los informes.
  FrontendBucketName:
    Type: String
    Description: Un nombre globalmente único para el bucket de S3 que alojará el frontend (ej. ai-job-agent-frontend-juanr).

Globals:
  Function:
    Timeout: 60
    Runtime: python3.9
    MemorySize: 256
    # ... (variables de entorno sin cambios) ...

Resources:
  # --- Frontend Hosting ---
  FrontendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref FrontendBucketName
      WebsiteConfiguration:
        IndexDocument: auth.html # La página de inicio será la de autenticación
        ErrorDocument: auth.html
  
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${FrontendBucket}/*"

  # --- Authentication ---
  CognitoUserPool:
    # ... (definición de User Pool sin cambios) ...
      
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # ... (otras propiedades sin cambios) ...
      # Las URLs ahora se construyen dinámicamente a partir de la URL del bucket S3
      CallbackURLs:
        - !Sub "${FrontendBucket.WebsiteURL}/dashboard.html"
      LogoutURLs:
        - !Sub "${FrontendBucket.WebsiteURL}/auth.html"
  
  # ... (resto de los recursos: S3 Buckets de datos, DynamoDB, Lambdas sin cambios) ...

Outputs:
  FrontendURL:
    Description: "La URL del frontend de la aplicación"
    Value: !GetAtt FrontendBucket.WebsiteURL
  # ... (otros outputs sin cambios) ...

